# Generated by Django 4.2.19 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='按钮名')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='图标')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父级菜单')),
                ('order_num', models.IntegerField(null=True, verbose_name='显示顺序')),
                ('path', models.CharField(max_length=300, null=True, verbose_name='路由地址')),
                ('menu_type', models.CharField(max_length=1, null=True, verbose_name='菜单类型')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='权限标识')),
            ],
            options={
                'verbose_name': '菜单表',
                'db_table': 'menu',
            },
        ),
    ]
