# Generated by Django 4.2.19 on 2025-07-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
    ]
