# Generated by Django 4.2.19 on 2025-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetDisk',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, verbose_name='访问地址')),
                ('fileName', models.CharField(max_length=255, verbose_name='文件名')),
                ('fileSize', models.CharField(max_length=255, verbose_name='文件大小')),
                ('isFold', models.BooleanField(default=False, verbose_name='是否是文件夹')),
            ],
            options={
                'verbose_name': '文件表',
                'db_table': 'net_disk',
            },
        ),
    ]
