# Generated by Django 4.2.19 on 2025-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('net_disk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetDisk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, verbose_name='访问地址')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父级地址')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.CharField(max_length=255, verbose_name='文件大小')),
                ('is_fold', models.BooleanField(default=False, verbose_name='是否是文件夹')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件表',
                'db_table': 'net_disk',
            },
        ),
    ]
