# Generated by Django 4.2.19 on 2025-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_disk', '0002_rename_filename_netdisk_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netdisk',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父级地址'),
        ),
    ]
