# Generated by Django 4.2.19 on 2025-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inteface',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='接口名')),
                ('type', models.IntegerField(null=True, verbose_name='接口类型')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='接口路径')),
            ],
            options={
                'verbose_name': '接口表',
                'db_table': 'inteface',
            },
        ),
    ]
