# Generated by Django 4.2.19 on 2025-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='角色名')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='角色权限字符串')),
                ('menus', models.ManyToManyField(related_name='roles', to='menu.menu')),
            ],
            options={
                'verbose_name': '角色表',
                'db_table': 'role',
            },
        ),
    ]
