# Generated by Django 4.2.19 on 2025-07-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20250716_1654'),
    ]

    operations = [
    ]
