# Generated by Django 4.2.19 on 2025-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('login_date', models.DateField(null=True, verbose_name='登陆时间')),
                ('status', models.IntegerField(null=True, verbose_name='状态值')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
