# Generated by Django 4.2.19 on 2025-06-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('login_date', models.DateField(null=True, verbose_name='登陆时间')),
                ('status', models.IntegerField(null=True, verbose_name='状态值')),
                ('roles', models.ManyToManyField(related_name='users', to='role.role')),
            ],
            options={
                'verbose_name_plural': '公共字段表',
                'db_table': 'BaseTable',
                'abstract': False,
            },
        ),
    ]
