# Generated by Django 4.2.19 on 2025-06-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
