# Generated by Django 4.2.19 on 2025-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='按钮名')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='标识')),
            ],
            options={
                'verbose_name': '按钮表',
                'db_table': 'button',
            },
        ),
    ]
