# Generated by Django 4.2.19 on 2025-07-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_initial'),
    ]

    operations = [
    ]
