# Generated by Django 4.2.19 on 2025-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintains',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100, null=True, verbose_name='设备名')),
                ('applyer', models.CharField(max_length=100, null=True, verbose_name='申请人')),
                ('maintainer', models.CharField(max_length=100, null=True, verbose_name='维修人员')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='主题')),
            ],
            options={
                'verbose_name': '维修表',
                'db_table': 'maintains',
            },
        ),
    ]
