# Generated by Django 4.2.19 on 2025-06-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
    ]
