# Generated by Django 4.2.19 on 2025-03-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_create_time_user_is_deleted_user_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('remark', models.CharField(max_length=2500, null=True, verbose_name='备注')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='角色名')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='角色权限字符串')),
            ],
            options={
                'verbose_name': '角色表',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.sysrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
            options={
                'db_table': 'sys_user_role',
            },
        ),
    ]
