# Generated by Django 4.2.19 on 2025-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('phoneNumber', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('loggin_date', models.DateField(null=True, verbose_name='登陆时间')),
                ('status', models.IntegerField(null=True, verbose_name='状态值')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=1200, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sysUser',
            },
        ),
    ]
