# Generated by Django 4.2.19 on 2025-02-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
    ]
