# Generated by Django 4.2.19 on 2025-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.CharField(max_length=2500, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
