# Generated by Django 4.2.19 on 2025-02-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_phonenumber_sysuser_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'verbose_name': '用户表'},
        ),
    ]
