# Generated by Django 4.2.19 on 2025-02-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysuser',
            table='sys_user',
        ),
    ]
