# Generated by Django 4.2.19 on 2025-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_loggin_date_sysuser_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
