# Generated by Django 4.2.19 on 2025-02-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysmenu',
            old_name='order_name',
            new_name='order_num',
        ),
    ]
